stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - flutter build apk --release --flavor dev -t lib/main_dev.dart --no-tree-shake-icons
    - cd android && bundle install
    - bundle exec fastlane move_files
  artifacts:
    paths:
      - build/artifacts/
  tags:
    - flutter
  variables:
    CI_DEBUG_TRACE: "true"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  dependencies:
    - build-job
  script:
    - cd android && bundle exec fastlane deploy_dev_firebase
  tags:
    - flutter
