variables:
  BUILD_FLAVOR: "dev"
  ENTRY_POINT: "main_dev.dart"

stages:          # List of stages for jobs, and their order of execution
  - pre-build
  - build
  - deploy

clean-job:
  stage: pre-build
  script:
    - flutter clean
    - flutter pub get
  tags:
    - flutter
    - abm
    - gais

build-job:       # This job runs in the build stage
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - if [ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "$CI_DEFAULT_BRANCH" ]; then
      export BUILD_FLAVOR="prod";ENTRY_POINT="main.dart";
      else if[ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "qa"]; then
      export BUILD_FLAVOR="stg";ENTRY_POINT="main_stg.dart";
      else
      echo "Condition not met, keeping MY_VARIABLE as is";
      fi
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo $BUILD_FLAVOR
    - echo $ENTRY_POINT
    - echo $CI_DEFAULT_BRANCH
    - flutter build apk --release --flavor $BUILD_FLAVOR -t lib/$ENTRY_POINT --no-tree-shake-icons
    - cd android
    - bundle update --bundler
    - bundle install
    - bundle exec fastlane move_files flavor:$BUILD_FLAVOR
  dependencies:
    - clean-job
  artifacts:
    paths:
      - build/artifacts/
  tags:
    - flutter
    - abm
    - gais
  variables:
    CI_DEBUG_TRACE: "true"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  dependencies:
    - build-job
  script:
    - if [ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "$CI_DEFAULT_BRANCH" ]; then
      export BUILD_FLAVOR="prod";ENTRY_POINT="main.dart";
      else if[ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "qa"]; then
      export BUILD_FLAVOR="stg";ENTRY_POINT="main_stg.dart";
      else
      echo "Condition not met, keeping MY_VARIABLE as is";
      fi
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo $BUILD_FLAVOR
    - echo $ENTRY_POINT
    - echo $CI_DEFAULT_BRANCH
    - echo printenv
    - cd android
    - bundle update --bundler
    - bundle install
    - bundle exec fastlane deploy_to_firebase flavor:$BUILD_FLAVOR --verbose
  tags:
    - flutter
    - abm
    - gais

